* Doom TODOs
** [ ] Fix colliding key bindings, especially C-s
The key bindings seem to be tweaked for Evil mode in particular, so they collide
with "vanilla" Emacs key bindings. Especially really basic ones, like Isearch,
which is not acceptable for my usage. (Too much muscle memory.)

[[file:~/.emacs.d/modules/term/eshell/config.el]]
** [X] Fix weird bug where for some reason flyspell is highlighting "correct" words
For example, "timezones" was getting highlighted, but Ispell was saying it was
actually correct. It appears that =--run-together= is the cause.

[[file:~/.emacs.d/modules/checkers/spell/config.el::(add-hook! 'text-mode-hook]]
*** Update: The problem was actually =--run-together= itself
It turns out "timezones" was a bad example, because it should have been the the
dictionary but just wasn't. The =--run-together= option was actually allowing
nonsense words like "timezoneapple", so I removed the option entirely.
** [ ] Script to install =vterm= dependencies
You can't build =vterm= until you have at least version 3.11 apparently. But it
seems Ubuntu 18.04 only ships with version 3.10.2.

https://apt.kitware.com/

You also need =libvterm=, but the correct version is downloaded during the
automatic build. The only catch is that you need =libtool-bin= to be installed
for that to work.
** [ ] Script to install Emacs
In the past I've been using =emacs-snapshot=, i.e., Emacs 28, but it hasn't been
very stable. (And causing =vterm= to segfault.) It would be better to use
Emacs 27. There's a PPA for that:

#+begin_src
$ sudo add-apt-repository ppa:kelleyk/emacs
$ sudo apt update
$ sudo apt install emacs27
#+end_src
